["E:\\projects\\gcli2api\\geminicli\\creds\\atomic-affinity-425012-f4-1755254085.json"]
error_codes = []
disabled = false
last_success = "2025-08-15T10:57:49.674992+00:00"

["E:\\projects\\gcli2api\\geminicli\\creds\\gemini-pro-1751713012-02f4ec0d-1755254085.json"]
error_codes = []
disabled = false

["E:\\projects\\gcli2api\\geminicli\\creds\\gemini-pro-1751713012-1cd0640c-1755254085.json"]
error_codes = []
disabled = false
